app/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
]

app/members/urls.py
from django.urls import path

from . import views


app_name = 'members'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout')
]

app/members/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    # profile_img = models.ImageField(
    #     upload_to='user/img/', blank=True, help_text='프로필 사진')
    phone = models.CharField(
        max_length=13, help_text='핸드폰 번호', blank=True)
    address = models.TextField(help_text='주소')

    # favorites = models.ManyToManyField(
    #     Keyword, through='Favorite', related_name='users', help_text='좋아요')

    class Meta:
        verbose_name = '유저'
        verbose_name_plural = '%s 목록' % verbose_name


class Favorite(models.Model):
    user = models.ForeignKey(
        'User', on_delete=models.CASCADE)
    # keyword = models.ForeignKey(
    #     Keyword, related_name='favorites', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = '좋아요'
        verbose_name_plural = '%s 목록' % verbose_name


class Keyword(models.Model):
    user = models.ForeignKey(
        'User', on_delete=models.CASCADE)
    # keyword = models.ForeignKey(
    #     Keyword, related_name='favorites', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = '키워'
        verbose_name_plural = '%s 목록' % verbose_name

app/members/forms.py
from django import forms
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django.core.exceptions import ValidationError


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'username': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'UserName 입력해주세요'}),
            'email': forms.EmailInput(
                attrs={'class': 'form-control', 'placeholder': 'Email 입력해주세요'}),
            'password': forms.PasswordInput(
                attrs={'class': 'form-control', 'placeholder': 'Password 입력해주세요'}),
        }
        labels = {
            'username': '닉네임',
            'email': '이메일',
            'password': '패스워드'
        }

    # 글자수 제한
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['maxlength'] = 15


class LoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': '이메일',
            }
        )
    )
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '아이디',
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '비밀번호',
            }
        )
    )

    def clean(self):
        # Form.clean에서는 cleaned_data에 접근 가능
        # cleaned_data에는
        #  이 Form이 가진 모든 Field들에서 리턴된 데이터가 key: value로 들어있음
        username = self.cleaned_data['username']
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']
        user = authenticate(email=email, username=username, password=password)
        if not user:
            raise ValidationError('username또는 password가 올바르지 않습니다.')
        return self.cleaned_data

    def login(self, request):
        email = self.cleaned_data['email']
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = authenticate(email=email, username=username, password=password)
        login(request, user)


# class SignupForm(forms.Form):
#     email = forms.EmailField(
#         widget=forms.EmailInput(
#             attrs={
#                 'class': 'form-control',
#                 'placeholder': '이메일',
#             }
#         )
#     )
#
#     username = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 'class': 'form-control',
#                 'placeholder': '사용자명',
#             }
#         )
#     )
#     password = forms.CharField(
#         widget=forms.PasswordInput(
#             attrs={
#                 'class': 'form-control',
#                 'placeholder': '비밀번호',
#             }
#         )
#     )
#
#     def clean_username(self):
#         username = self.cleaned_data['username']
#         if User.objects.filter(username=username).exists():
#             raise ValidationError('이미 사용중인 username입니다')
#         return username
#
#     def clean_email(self):
#         email = self.cleaned_data['email']
#         if User.objects.filter(email=email).exists():
#             raise ValidationError('이미 사용중인 email입니다')
#         return email
#
#     def save(self):
#         """
#         Form으로 전달받은 데이터를 사용해서
#         새로운 User를 생성하고 리턴
#         """
#         return User.objects.create_user(
#             username=self.cleaned_data['username'],
#             email=self.cleaned_data['email'],
#             password=self.cleaned_data['password'],
#         )

class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ['username', 'email', 'password', ]

app/members/views.py
from django.contrib.auth import login
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView

from members.models import User
from .forms import UserForm, LoginForm


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            form.login(request)
            return redirect('members:index')

    else:
        form = LoginForm()
        context = {
            'form': form,
        }
        return render(request, 'members/login.html', context)


def signup_view(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('members:index')
        else:
            return HttpResponse('이미 존재하는 USER 입니다.')
    else:
        form = UserForm()

        context = {
            'form': form,
        }
        return render(request, 'members/signup.html', {'form': form})


def index(request):
    return render(request, 'index.html')


def logout_view(request):
    pass

app/templates/base.html
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}">
    <title>Smart Market</title>
    {% block head %}{% endblock %}
    <style>
        html {
            font-size: .9rem;
        }
    </style>
</head>
<body>
    <div id="wrap">
        <nav class="navbar navbar-expand navbar-dark bg-dark">
            <a href="{% url 'members:signup' %}" class="navbar-brand">Smart Market</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="#" class="nav-link">{{ user.username }}</a>
                        </li>
<!--                        <li class="nav-item">-->
<!--                            <a href="{% url 'members:logout' %}" class="nav-link">Logout</a>-->
<!--                        </li>-->
                    {% else %}
                        <li class="nav-item">
                            <a href="{% url 'members:login' %}" class="nav-link">Login</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a href="{% url 'members:signup' %}" class="nav-link text-white btn btn-primary btn-sm">+ Add Post</a>
                    </li>
                </ul>
            </div>
        </nav>

        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

app/templates/index.html
asdfasdf

app/templates/members/login.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
    <div class="container-fluid">
            <div class="mr-auto ml-auto mt-3
                        col-lg-4
                        col-md-6
                        col-sm-8
                        col-10">
                <div class="card text-center p-4">
                    <h1>Smart Market</h1>
                    <form action="{% url 'members:login' %}" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{field}}
                            </div>
                        {% endfor %}
                        {% if form.non_field_errors %}
                            <ul class="list-unstyled text-danger">
                                {% for error in form.non_field_errors %}
                                    <li>{{ error|escape }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <button class="btn btn-primary btn-block">로그인</button>
                    </form>
                    <hr>
                    <a  href="{{ login_url }}"
                        class="btn btn-block btn-outline-success mb-3">NAVER로 로그인</a>
                    <a href="">비밀번호를 잊으셨나요?</a>
                </div>

                <div class="card text-center p-4 mt-3 mb-3">
                    <span>계정이 없으신가요?</span>
                    <a href="{% url 'members:signup' %}">가입하기</a>
               </div>
            </div>
    </div>
{% endblock %}

app/templates/members/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="mr-auto ml-auto mt-3
                    col-lg-4
                    col-md-6
                    col-sm-8
                    col-10">
            <div class="card text-center p-4">
                <h1>Smart Market</h1>
                <p class="text-secondary">친구들의 사진과 동영상을 보려면 가입하세요</p>
                <button class="btn btn-primary btn-block">Facebook으로 로그인</button>
                <hr>
                <form method="POST" action="{% url 'members:signup' %}" class="sign-up-form">
                    {%csrf_token%}
                    <h2 class="sub-title"> 회원가입 </h2>
                    {% for field in form %}
                        <div class="form-group">
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">가입</button>
                </form>
                <p class="text-secondary">가입하면 Smart Market 약관 데이터 정책 및 쿠키 정책에 동의하게 됩니다</p>
            </div>

            <div class="card text-center p-4 mt-3 mb-3">
                <span>계정이 있으신가요?</span>
                <a href="{% url 'members:login' %}">로그인</a>
            </div>
        </div>
    </div>
{% endblock %}